// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as TimePicker } from 'antd/es/time-picker/index.js';
export type { TimePickerProps } from 'antd/es/time-picker/index.js';
