// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as TreeSelect } from 'antd/es/tree-select/index.js';
export type { TreeSelectProps } from 'antd/es/tree-select/index.js';
