// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as Splitter } from 'antd/es/splitter/index.js';
export type { SplitterProps } from 'antd/es/splitter/index.js';
