// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as Watermark } from 'antd/es/watermark/index.js';
export type { WatermarkProps } from 'antd/es/watermark/index.js';
