// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as Typography } from 'antd/es/typography/index.js';
export type { TypographyProps } from 'antd/es/typography/index.js';
