// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as Carousel } from 'antd/es/carousel/index.js';
export type { CarouselProps } from 'antd/es/carousel/index.js';
