// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as ColorPicker } from 'antd/es/color-picker/index.js';
export type { ColorPickerProps } from 'antd/es/color-picker/index.js';
