import type { Metadata } from 'next'
import type { ReactNode } from 'react'
import type { TOCItemType } from 'fumadocs-core/toc'
import { notFound } from 'next/navigation'

import { headingSizeClass } from '@nanisoft/prism-ui/components/section'

import { ApiTable } from '@/components/api-table'
import { CatalogueIndex } from '@/components/catalogue-index'
import { DocsShell } from '@/components/docs-shell'
import { ItemHeader } from '@/components/item-header'
import { JsonLd } from '@/components/json-ld'
import { getMDXComponents } from '@/components/mdx'
import type { CataloguePageData } from '@/lib/catalogue'
import { kindLabel } from '@/lib/kinds'
import { flattenNav, projectNav } from '@/lib/nav'
import { SITE_NAME, SITE_URL } from '@/lib/site'
import { source } from '@/lib/source'

export function generateStaticParams() {
  return source.generateParams()
}

export const dynamicParams = false

/**
 * What a page says about itself to a search engine.
 *
 * **The description is the page's own lede rather than a summary written here.**
 * Every prose page and every Item already carries one in its frontmatter, and a
 * second sentence written here would be the one a reader sees in a result and
 * the one nobody edits when the page changes. Falling back to the site's
 * description rather than to nothing is deliberate: a page with no description
 * gets a search engine's invented one, and this is at least true.
 *
 * **The canonical is the route the tree produced, absolute.** Under a static
 * export every page is served from the same origin, so the only canonical that
 * carries information is the one that names the path: without it a reader who
 * arrives at `/components/button?category=feedback` and one who arrives at
 * `/components/button` are two URLs for one page, and the filter's query
 * parameter is a view of the catalogue rather than a page of its own.
 *
 * `openGraph` repeats the same three values rather than inheriting them. The root
 * layout sets them for the landing page, and metadata does not merge deeply enough
 * to carry an `openGraph` object down to every page without restating it at each
 * one, which is what a share card of a documentation page is made of.
 */
export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string[] }>
}): Promise<Metadata> {
  const { slug } = await params
  const page = source.getPage(slug)
  if (!page) return {}

  const title = (page.data.title as string | undefined) ?? undefined
  const description = (page.data.description as string | undefined) ?? undefined
  const url = new URL(page.url, SITE_URL).href

  return {
    title,
    description,
    alternates: { canonical: page.url },
    openGraph: { type: 'article', url, siteName: SITE_NAME, title, description },
    twitter: { card: 'summary_large_image', title, description },
  }
}

type ProseBody = (props: { components?: Record<string, unknown> }) => ReactNode

/**
 * What every page in the routed tree carries.
 *
 * `kind`, `category`, `status`, `exports`, `source`, `slug` and `name` are the
 * Catalogue's words, merged into an Item page's data by `content-tree.ts` from
 * `buildCatalog()`. The collection's schema strips a `kind` or a `category` out
 * of frontmatter, so this cast reads a shape a maintainer cannot write into a
 * file: the discriminator below is a key only the merge adds, which is why
 * "is this an Item page" is answered by the data rather than by which collection
 * or which loader the page came from.
 */
type RoutedData = Partial<CataloguePageData> & {
  /** The file opens with its own heading, so the frame adds none. */
  selfTitled?: boolean
  body?: ProseBody
  toc?: TOCItemType[]
}

export default async function Page({ params }: { params: Promise<{ slug: string[] }> }) {
  const { slug } = await params
  const page = source.getPage(slug)

  // The canonical fumadocs check, before returning and never inside a Suspense
  // boundary, so an unknown slug is a real not-found rather than a soft 404.
  if (!page) notFound()

  // The tree is the navigation's one source, read here because this is the one
  // module that can: the routing tree is compiled by the bundler plugin, so it
  // does not exist outside it. The projection refuses to return a partial
  // navigation, which is what turns a page the ordering forgot into a failed
  // render rather than a green build with a page missing from the sidebar.
  const sections = projectNav(source.getPageTree())
  const flat = flattenNav(sections)
  const components = getMDXComponents()
  const data = page.data as RoutedData

  // A Section landing page, generated by the Catalogue because no file says what
  // the Section holds. It is the only page with no body, and it is the only page
  // a reader reaches at a Section's own route.
  if (data.sectionIndex === true && data.kind !== undefined) {
    return (
      <CatalogueIndex kind={data.kind} sections={sections} flat={flat} currentUrl={page.url} />
    )
  }

  // An Item page is its documentation, read by the one collection and carrying
  // the Catalogue's words. The body is the file's own, so there is no second
  // collection to look in and no slug to join: the page a reader got and the
  // document that holds its prose are one thing.
  if (data.kind !== undefined && data.slug !== undefined) {
    const ItemBody = data.body
    const name = data.name ?? data.title ?? data.slug
    return (
      <DocsShell sections={sections} currentUrl={page.url} flat={flat} toc={data.toc}>
        {/*
          The item as a technical article, which is what it is: a document about
          a component, with a name, a summary and a place in the site. Every
          value is the catalogue's own word or the route the tree produced, so
          nothing here can drift from the page it describes. There is no date and
          no author beyond the organisation, because the site publishes neither
          and a structured-data field asserting one would be a claim the page
          cannot support.
        */}
        <JsonLd
          data={{
            '@context': 'https://schema.org',
            '@type': 'TechArticle',
            headline: name,
            description: data.description ?? undefined,
            url: new URL(page.url, SITE_URL).href,
            articleSection: data.category ?? kindLabel(data.kind),
            isPartOf: { '@id': `${SITE_URL.href}#website` },
            publisher: { '@id': `${SITE_URL.href}#organization` },
          }}
        />
        <ItemHeader
          name={name}
          description={data.description ?? ''}
          kind={data.kind}
          category={data.category ?? null}
          status={data.status ?? 'stable'}
        />

        {/*
          One article, and the appendix heading is a section of it.

          The heading said `text-xl`, which put an `h2` at 20 pixels under the prose
          `h2` at 30 and below the prose `h3` at 24 above it, so the page carried
          three heading tiers where the frame and the article carry two between them.
          Asking `headingSizeClass` for the level it renders answered that and put it
          on the wrong ladder: it is an `h2` of an article, so it takes the article's
          ladder, and the Block ladder is a step and a half above it at `sm`. An
          appendix heading at 48 pixels is the second largest thing on a page whose
          three content sections are at 30, and the outline said so in the order the
          reader meets it.

          So it is written into the article rather than beside it. `.prose` is where
          the site's prose ladder lives, at the steps `Prose` itself uses, and MDX
          hands it plain tags, so a heading that belongs to the article belongs inside
          the wrapper that owns the article's typography. It carries no class at all:
          every section heading in this article is a bare `<h2>` the article styles,
          and a heading that named its own step would be the second answer to a
          question the article has already answered. `DESIGN.md` under Typography,
          Hierarchy states that the two ladders differ by 1.6 at `sm` and which to
          reach for, so the divergence is documented rather than left to be found.

          The table stays outside `.prose`, because that wrapper's rules reach every
          descendant and `.prose td` would put the API table's cells at `--text-base`
          and in the muted colour, which is the article's body treatment and not a
          table's. The `gap-4` is the article's own block rhythm, the same 16 pixels
          `.prose > * + *` gives every other block in the body, so the appendix reads
          as part of the article rather than as a second region under it.
        */}
        <div className="flex flex-col gap-4">
          <div className="prose">
            {ItemBody ? <ItemBody components={components} /> : null}
            <h2>API reference</h2>
          </div>
          <ApiTable slug={data.slug} />
        </div>
      </DocsShell>
    )
  }

  const Body = data.body

  return (
    <DocsShell sections={sections} currentUrl={page.url} flat={flat} toc={data.toc}>
      {/*
        A page that declares its title in frontmatter has no heading of its own,
        so the frame prints one. A generated page is a published package's own
        `CHANGELOG.md`, byte for byte, and that file begins with the package's
        name: the heading is already in the body, and printing a second one
        above it is the same heading twice. Nothing is dropped from the file
        either way, which is the property the Section is for.

        The header matches `ItemHeader`'s exactly, and it is the same markup for a
        reason: a reader moving between a prose page and an Item page was
        previously looking at two different title treatments, and the difference
        told them nothing except that the pages came from different folders.
      */}
      {data.selfTitled ? null : (
        <header className="border-border flex flex-col gap-3 border-b pb-8">
          <h1 className={`font-semibold tracking-tight text-balance ${headingSizeClass('h1')}`}>
            {data.title}
          </h1>
          {data.description ? (
            <p className="text-muted-foreground max-w-measure text-lg text-pretty">
              {data.description}
            </p>
          ) : null}
        </header>
      )}

      {Body ? (
        <div className="prose">
          <Body components={components} />
        </div>
      ) : null}
    </DocsShell>
  )
}
