// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as Breadcrumb } from 'antd/es/breadcrumb/index.js';
export type { BreadcrumbProps } from 'antd/es/breadcrumb/index.js';
