'use client';

// The app-level Demo component (ticket 12 §2): resolves a registry id —
// `<section>/<item>/<example-slug>` — to its co-located demos/<slug>.tsx and
// renders the live preview + copy/expand wire. The registry is generated by
// scripts/generate.mjs, so prism-ui never touches fs and the MDX never carries
// code. Keeping this boundary client-side also lets demos pass ordinary
// function props (for example DataTable's row-key callback) without crossing
// React's server-to-client serialization boundary.

import { DemoView } from '@/components/DemoView';
import { demos } from '@/lib/generated/demos';

export function Demo({ id }: { id: string }) {
  const entry = demos[id];
  if (!entry) {
    return (
      <div className="site-demo-missing" role="note">
        <strong>This example is not available in the browser yet.</strong>
        <span>
          The page still documents the import contract. Use the Prism MCP for the API, or open the source
          file <code>{id}</code> when it is added to the corpus.
        </span>
      </div>
    );
  }
  return (
    <DemoView code={entry.code}>
      <entry.Component />
    </DemoView>
  );
}
