// The app-level Demo component (ticket 12 §2): resolves a registry id —
// `<section>/<item>/<example-slug>` — to its co-located demos/<slug>.tsx and
// renders the live preview + copy/expand wire. The registry is generated by
// scripts/generate.mjs, so prism-ui never touches fs and the MDX never carries
// code.

import { DemoView } from '@/components/DemoView';
import { demos } from '@/lib/generated/demos';

export function Demo({ id }: { id: string }) {
  const entry = demos[id];
  if (!entry) {
    return (
      <p className="site-demo-missing">
        No demo registered for <code>{id}</code> — add <code>demos/&lt;slug&gt;.tsx</code> next to the
        doc page and re-run <code>pnpm generate</code>.
      </p>
    );
  }
  return (
    <DemoView code={entry.code}>
      <entry.Component />
    </DemoView>
  );
}
