// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as Statistic } from 'antd/es/statistic/index.js';
export type { StatisticProps } from 'antd/es/statistic/index.js';
