// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as DatePicker } from 'antd/es/date-picker/index.js';
export type { DatePickerProps } from 'antd/es/date-picker/index.js';
