// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as FloatButton } from 'antd/es/float-button/index.js';
export type { FloatButtonProps } from 'antd/es/float-button/index.js';
