// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as Mentions } from 'antd/es/mentions/index.js';
export type { MentionsProps } from 'antd/es/mentions/index.js';
