// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as Calendar } from 'antd/es/calendar/index.js';
export type { CalendarProps } from 'antd/es/calendar/index.js';
