// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as Cascader } from 'antd/es/cascader/index.js';
export type { CascaderProps } from 'antd/es/cascader/index.js';
