/**
 * The checked Prism catalogue: the single list of Components, Blocks and Pages.
 *
 * This is the shape fixed by tickets 09 and 19, not the finished 28-item roster.
 * The v1 build grows it one authored entry at a time; `source` and `exports` are
 * the fields the build checks against disk and the emitted declarations, never
 * the reverse, so the internal shadcn registry stays derived rather than
 * authoritative. Tooling only: a consumer's runtime UI must not import this.
 */

export const CATALOG_KINDS = ['component', 'block', 'page'] as const
export type CatalogKind = (typeof CATALOG_KINDS)[number]

export const COMPONENT_CATEGORIES = [
  'Call to action',
  'Forms and inputs',
  'Feedback',
  'Layout',
  'Data display',
  'Typography',
  'Miscellaneous',
] as const
export type ComponentCategory = (typeof COMPONENT_CATEGORIES)[number]

export interface CatalogItem {
  name: string
  slug: string
  kind: CatalogKind
  category: ComponentCategory | null
  description: string
  source: string
  exports: string[]
  status: 'stable' | 'deprecated'
}

export const catalog: readonly CatalogItem[] = [
  {
    name: 'Button',
    slug: 'button',
    kind: 'component',
    category: 'Call to action',
    description: 'The action control for commands, links and loading states.',
    source: 'src/components/ui/button.tsx',
    exports: ['Button'],
    status: 'stable',
  },
  {
    name: 'CtaLink',
    slug: 'cta-link',
    kind: 'component',
    category: 'Call to action',
    description: 'The call to action that goes somewhere: a native link carrying the weight of a button.',
    source: 'src/components/ui/cta-link.tsx',
    exports: ['CtaLink'],
    status: 'stable',
  },
  {
    name: 'Badge',
    slug: 'badge',
    kind: 'component',
    category: 'Data display',
    description: 'A compact status or category label.',
    source: 'src/components/ui/badge.tsx',
    exports: ['Badge'],
    status: 'stable',
  },
  {
    name: 'Card',
    slug: 'card',
    kind: 'component',
    category: 'Data display',
    description: 'A bordered surface for a small group of related content.',
    source: 'src/components/ui/card.tsx',
    exports: ['Card', 'CardHeader', 'CardTitle', 'CardDescription', 'CardContent', 'CardFooter'],
    status: 'stable',
  },
  {
    name: 'Section',
    slug: 'section',
    kind: 'component',
    category: 'Layout',
    description: 'The container and heading primitives every Block composes for rhythm.',
    source: 'src/components/ui/section.tsx',
    exports: ['Section', 'SectionHeading'],
    status: 'stable',
  },
  {
    name: 'Breadcrumb',
    slug: 'breadcrumb',
    kind: 'component',
    category: 'Call to action',
    description: 'The trail of ancestor links that shows where the current page sits.',
    source: 'src/components/ui/breadcrumb.tsx',
    exports: [
      'Breadcrumb',
      'BreadcrumbList',
      'BreadcrumbItem',
      'BreadcrumbLink',
      'BreadcrumbPage',
      'BreadcrumbSeparator',
    ],
    status: 'stable',
  },
  {
    name: 'Pagination',
    slug: 'pagination',
    kind: 'component',
    category: 'Call to action',
    description: 'The control that moves between pages of a paged collection.',
    source: 'src/components/ui/pagination.tsx',
    exports: [
      'Pagination',
      'PaginationContent',
      'PaginationItem',
      'PaginationLink',
      'PaginationPrevious',
      'PaginationNext',
      'PaginationEllipsis',
    ],
    status: 'stable',
  },
  {
    name: 'Field',
    slug: 'field',
    kind: 'component',
    category: 'Forms and inputs',
    description: 'The labelled wrapper that pairs a form control with its label, description and error.',
    source: 'src/components/ui/field.tsx',
    exports: ['Field', 'FieldLabel', 'FieldDescription', 'FieldError', 'FieldGroup'],
    status: 'stable',
  },
  {
    name: 'Input',
    slug: 'input',
    kind: 'component',
    category: 'Forms and inputs',
    description: 'The single-line text control for a form.',
    source: 'src/components/ui/input.tsx',
    exports: ['Input'],
    status: 'stable',
  },
  {
    name: 'Textarea',
    slug: 'textarea',
    kind: 'component',
    category: 'Forms and inputs',
    description: 'The multi-line text control for a form.',
    source: 'src/components/ui/textarea.tsx',
    exports: ['Textarea'],
    status: 'stable',
  },
  {
    name: 'Alert',
    slug: 'alert',
    kind: 'component',
    category: 'Feedback',
    description: 'A static callout that carries an important message to the reader.',
    source: 'src/components/ui/alert.tsx',
    exports: ['Alert', 'AlertTitle', 'AlertDescription'],
    status: 'stable',
  },
  {
    name: 'Skeleton',
    slug: 'skeleton',
    kind: 'component',
    category: 'Feedback',
    description: 'A placeholder surface that mirrors the shape of content while it loads.',
    source: 'src/components/ui/skeleton.tsx',
    exports: ['Skeleton'],
    status: 'stable',
  },
  {
    name: 'LiveRegion',
    slug: 'live-region',
    kind: 'component',
    category: 'Feedback',
    description: 'A region that announces what just changed in it, and renders nothing when it has nothing to say.',
    source: 'src/components/ui/live-region.tsx',
    exports: ['LiveRegion'],
    status: 'stable',
  },
  {
    name: 'Separator',
    slug: 'separator',
    kind: 'component',
    category: 'Layout',
    description: 'A hairline rule that divides content, horizontally or vertically.',
    source: 'src/components/ui/separator.tsx',
    exports: ['Separator'],
    status: 'stable',
  },
  {
    name: 'Table',
    slug: 'table',
    kind: 'component',
    category: 'Data display',
    description: 'The semantic table components for rows, columns and captions.',
    source: 'src/components/ui/table.tsx',
    exports: [
      'Table',
      'TableHeader',
      'TableBody',
      'TableFooter',
      'TableRow',
      'TableHead',
      'TableCell',
      'TableCaption',
    ],
    status: 'stable',
  },
  {
    name: 'Typography',
    slug: 'typography',
    kind: 'component',
    category: 'Typography',
    description: 'The text and heading components that apply the type scale.',
    source: 'src/components/ui/typography.tsx',
    exports: ['Text', 'Heading'],
    status: 'stable',
  },
  {
    name: 'Kbd',
    slug: 'kbd',
    kind: 'component',
    category: 'Typography',
    description: 'The inline label for a keyboard key or shortcut.',
    source: 'src/components/ui/kbd.tsx',
    exports: ['Kbd'],
    status: 'stable',
  },
  {
    name: 'Mark',
    slug: 'mark',
    kind: 'component',
    category: 'Typography',
    description: 'A run of text with its matches visibly marked, and nothing announced.',
    source: 'src/components/ui/mark.tsx',
    exports: ['Mark'],
    status: 'stable',
  },
  {
    name: 'Tree',
    slug: 'tree',
    kind: 'component',
    category: 'Layout',
    description: 'A tree of nodes given as data, navigable by the arrow keys.',
    source: 'src/components/ui/tree.tsx',
    exports: ['Tree'],
    status: 'stable',
  },
  {
    name: 'Diagram',
    slug: 'diagram',
    kind: 'component',
    category: 'Data display',
    description:
      'Named things and the labelled relations between them, drawn as inline vector markup whose every stroke and fill is a token.',
    source: 'src/components/ui/diagram.tsx',
    exports: ['Diagram'],
    status: 'stable',
  },
  {
    name: 'ProductMark',
    slug: 'product-mark',
    kind: 'component',
    category: 'Data display',
    description:
      "A product's two-part colour mark: a brand-ink ring around the pack's own fill, beside the product's name in the brand ink.",
    source: 'src/components/ui/product-mark.tsx',
    exports: ['ProductMark'],
    status: 'stable',
  },
  {
    name: 'Prose',
    slug: 'prose',
    kind: 'component',
    category: 'Typography',
    description:
      'Consumer-authored body copy held to the reading measure and to the block rhythm, so a document does not restate either.',
    source: 'src/components/ui/prose.tsx',
    exports: ['Prose'],
    status: 'stable',
  },
  {
    name: 'FactList',
    slug: 'fact-list',
    kind: 'component',
    category: 'Data display',
    description:
      'A short list of named facts as a definition list, where a value may be a link and the term column stays aligned down its length.',
    source: 'src/components/ui/fact-list.tsx',
    exports: ['FactList'],
    status: 'stable',
  },
  {
    name: 'ProductSwitcher',
    slug: 'product-switcher',
    kind: 'component',
    category: 'Layout',
    description:
      'A switch between the members of a set of products, each drawn with its own ProductMark and the current one marked aria-current.',
    source: 'src/components/ui/product-switcher.tsx',
    exports: ['ProductSwitcher'],
    status: 'stable',
  },
  {
    name: 'Select',
    slug: 'select',
    kind: 'component',
    category: 'Forms and inputs',
    description: 'The control that chooses one option from a list that opens on demand.',
    source: 'src/components/ui/select.tsx',
    exports: [
      'Select',
      'SelectTrigger',
      'SelectValue',
      'SelectContent',
      'SelectItem',
      'SelectGroup',
      'SelectLabel',
      'SelectSeparator',
    ],
    status: 'stable',
  },
  {
    name: 'Checkbox',
    slug: 'checkbox',
    kind: 'component',
    category: 'Forms and inputs',
    description: 'The control for an independent yes-or-no choice, with an optional mixed state.',
    source: 'src/components/ui/checkbox.tsx',
    exports: ['Checkbox'],
    status: 'stable',
  },
  {
    name: 'RadioGroup',
    slug: 'radio-group',
    kind: 'component',
    category: 'Forms and inputs',
    description: 'The control that chooses exactly one option from a small visible set.',
    source: 'src/components/ui/radio-group.tsx',
    exports: ['RadioGroup', 'RadioGroupItem'],
    status: 'stable',
  },
  {
    name: 'Switch',
    slug: 'switch',
    kind: 'component',
    category: 'Forms and inputs',
    description: 'The control that turns a setting on or off immediately.',
    source: 'src/components/ui/switch.tsx',
    exports: ['Switch'],
    status: 'stable',
  },
  {
    name: 'Slider',
    slug: 'slider',
    kind: 'component',
    category: 'Forms and inputs',
    description: 'The control that chooses a number along a range.',
    source: 'src/components/ui/slider.tsx',
    exports: ['Slider'],
    status: 'stable',
  },
  {
    name: 'Progress',
    slug: 'progress',
    kind: 'component',
    category: 'Feedback',
    description: 'The bar that reports how far a task has progressed.',
    source: 'src/components/ui/progress.tsx',
    exports: ['Progress'],
    status: 'stable',
  },
  {
    name: 'Meter',
    slug: 'meter',
    kind: 'component',
    category: 'Feedback',
    description: 'A bounded measure drawn as a scale, with the limits the caller cares about marked on it.',
    source: 'src/components/ui/meter.tsx',
    exports: ['Meter'],
    status: 'stable',
  },
  {
    name: 'Tooltip',
    slug: 'tooltip',
    kind: 'component',
    category: 'Feedback',
    description: 'The short label shown on hover or focus beside a control.',
    source: 'src/components/ui/tooltip.tsx',
    exports: ['Tooltip', 'TooltipTrigger', 'TooltipContent'],
    status: 'stable',
  },
  {
    name: 'Accordion',
    slug: 'accordion',
    kind: 'component',
    category: 'Layout',
    description: 'The stack of headers that each reveal a panel in place.',
    source: 'src/components/ui/accordion.tsx',
    exports: ['Accordion', 'AccordionItem', 'AccordionTrigger', 'AccordionContent'],
    status: 'stable',
  },
  {
    name: 'Dialog',
    slug: 'dialog',
    kind: 'component',
    category: 'Layout',
    description: 'The modal surface for a decision or a short task, with a side-anchored sheet variant.',
    source: 'src/components/ui/dialog.tsx',
    exports: [
      'Dialog',
      'DialogTrigger',
      'DialogContent',
      'DialogHeader',
      'DialogFooter',
      'DialogTitle',
      'DialogDescription',
      'DialogClose',
    ],
    status: 'stable',
  },
  {
    name: 'DropdownMenu',
    slug: 'dropdown-menu',
    kind: 'component',
    category: 'Layout',
    description: 'The menu of actions and choices opened from one trigger.',
    source: 'src/components/ui/dropdown-menu.tsx',
    exports: [
      'DropdownMenu',
      'DropdownMenuTrigger',
      'DropdownMenuContent',
      'DropdownMenuItem',
      'DropdownMenuCheckboxItem',
      'DropdownMenuRadioGroup',
      'DropdownMenuRadioItem',
      'DropdownMenuLabel',
      'DropdownMenuSeparator',
      'DropdownMenuGroup',
      'DropdownMenuSub',
      'DropdownMenuSubTrigger',
      'DropdownMenuSubContent',
    ],
    status: 'stable',
  },
  {
    name: 'Popover',
    slug: 'popover',
    kind: 'component',
    category: 'Layout',
    description: 'The anchored floating surface for content richer than a tooltip.',
    source: 'src/components/ui/popover.tsx',
    exports: ['Popover', 'PopoverTrigger', 'PopoverContent'],
    status: 'stable',
  },
  {
    name: 'Tabs',
    slug: 'tabs',
    kind: 'component',
    category: 'Layout',
    description: 'The set of peer views shown one at a time.',
    source: 'src/components/ui/tabs.tsx',
    exports: ['Tabs', 'TabsList', 'TabsTrigger', 'TabsContent'],
    status: 'stable',
  },
  {
    name: 'Avatar',
    slug: 'avatar',
    kind: 'component',
    category: 'Data display',
    description: 'The person or entity image with an initials fallback.',
    source: 'src/components/ui/avatar.tsx',
    exports: ['Avatar', 'AvatarImage', 'AvatarFallback'],
    status: 'stable',
  },
  {
    name: 'Hero01',
    slug: 'hero-01',
    kind: 'block',
    category: null,
    description: 'A centered marketing hero with an optional eyebrow and one or two actions.',
    source: 'src/blocks/hero-01/index.tsx',
    exports: ['Hero01'],
    status: 'stable',
  },
  {
    name: 'FeatureGrid01',
    slug: 'feature-grid-01',
    kind: 'block',
    category: null,
    description: 'A feature grid with optional icon tiles and a section heading.',
    source: 'src/blocks/feature-grid-01/index.tsx',
    exports: ['FeatureGrid01'],
    status: 'stable',
  },
  {
    name: 'Stats01',
    slug: 'stats-01',
    kind: 'block',
    category: null,
    description: 'A KPI row with optional directional deltas.',
    source: 'src/blocks/stats-01/index.tsx',
    exports: ['Stats01'],
    status: 'stable',
  },
  {
    name: 'Pricing01',
    slug: 'pricing-01',
    kind: 'block',
    category: null,
    description: 'A plan comparison with one highlighted tier.',
    source: 'src/blocks/pricing-01/index.tsx',
    exports: ['Pricing01'],
    status: 'stable',
  },
  {
    name: 'Cta01',
    slug: 'cta-01',
    kind: 'block',
    category: null,
    description: 'A closing call to action on a filled primary surface.',
    source: 'src/blocks/cta-01/index.tsx',
    exports: ['Cta01'],
    status: 'stable',
  },
  {
    name: 'PageHeader01',
    slug: 'page-header-01',
    kind: 'block',
    category: null,
    description: 'A page title band with a breadcrumb trail, a supporting line and a row of actions.',
    source: 'src/blocks/page-header-01/index.tsx',
    exports: ['PageHeader01'],
    status: 'stable',
  },
  {
    name: 'DataTable01',
    slug: 'data-table-01',
    kind: 'block',
    category: null,
    description: 'A table section with a toolbar, filters, row selection and pagination.',
    source: 'src/blocks/data-table-01/index.tsx',
    exports: ['DataTable01'],
    status: 'stable',
  },
  {
    name: 'SettingsPanel01',
    slug: 'settings-panel-01',
    kind: 'block',
    category: null,
    description: 'A settings form grouped into sections of text, select and switch fields.',
    source: 'src/blocks/settings-panel-01/index.tsx',
    exports: ['SettingsPanel01'],
    status: 'stable',
  },
  {
    name: 'AuthForm01',
    slug: 'auth-form-01',
    kind: 'block',
    category: null,
    description: 'A sign-in card with labelled credential fields, a remember control and an error slot.',
    source: 'src/blocks/auth-form-01/index.tsx',
    exports: ['AuthForm01'],
    status: 'stable',
  },
  {
    name: 'AppShell01',
    slug: 'app-shell-01',
    kind: 'block',
    category: null,
    description: 'A navigation shell with a desktop rail, a top bar and a mobile navigation sheet.',
    source: 'src/blocks/app-shell-01/index.tsx',
    exports: ['AppShell01'],
    status: 'stable',
  },
  {
    name: 'ProcessRail01',
    slug: 'process-rail-01',
    kind: 'block',
    category: null,
    description:
      'A process drawn as a rail: two, three or four steps on one line, each with an ordinal, a name and one caption.',
    source: 'src/blocks/process-rail-01/index.tsx',
    exports: ['ProcessRail01'],
    status: 'stable',
  },
  {
    name: 'StatusLedger01',
    slug: 'status-ledger-01',
    kind: 'block',
    category: null,
    description:
      'A ledger of things and the state each is in: a name, one of four status tiers and the words for that tier.',
    source: 'src/blocks/status-ledger-01/index.tsx',
    exports: ['StatusLedger01'],
    status: 'stable',
  },
  {
    name: 'ProductGrid01',
    slug: 'product-grid-01',
    kind: 'block',
    category: null,
    description:
      'A set of products as hairline rows: a two-part ProductMark, a name, one tagline and a destination per row.',
    source: 'src/blocks/product-grid-01/index.tsx',
    exports: ['ProductGrid01'],
    status: 'stable',
  },
  {
    name: 'StackGrid01',
    slug: 'stack-grid-01',
    kind: 'block',
    category: null,
    description:
      'A survey of what a product is assembled from, and a second grid of what it built itself.',
    source: 'src/blocks/stack-grid-01/index.tsx',
    exports: ['StackGrid01'],
    status: 'stable',
  },
  {
    name: 'LogoStrip01',
    slug: 'logo-strip-01',
    kind: 'block',
    category: null,
    description:
      'A single line of short phrases: the transition band between a hero and the section that follows it.',
    source: 'src/blocks/logo-strip-01/index.tsx',
    exports: ['LogoStrip01'],
    status: 'stable',
  },
  {
    name: 'NoteGrid01',
    slug: 'note-grid-01',
    kind: 'block',
    category: null,
    description: 'A grid of short points: a title and a sentence or two, with no tile and no icon.',
    source: 'src/blocks/note-grid-01/index.tsx',
    exports: ['NoteGrid01'],
    status: 'stable',
  },
  {
    name: 'InstrumentPanel01',
    slug: 'instrument-panel-01',
    kind: 'block',
    category: null,
    description:
      'A bordered panel with a titled bar, a state dot with the words beside it, and a slot for the instrument.',
    source: 'src/blocks/instrument-panel-01/index.tsx',
    exports: ['InstrumentPanel01'],
    status: 'stable',
  },
  {
    name: 'SiteHeader',
    slug: 'site-header',
    kind: 'block',
    category: null,
    description:
      'The bar at the top of a product site: a brand lockup, an optional product switcher, the site navigation and a slot for application controls.',
    source: 'src/blocks/site-header/index.tsx',
    exports: ['SiteHeader'],
    status: 'stable',
  },
  {
    name: 'SiteFooter',
    slug: 'site-footer',
    kind: 'block',
    category: null,
    description:
      'The block at the foot of a product site: a brand lockup, grouped destinations, the links that leave the site and a slot for the legal line.',
    source: 'src/blocks/site-footer/index.tsx',
    exports: ['SiteFooter'],
    status: 'stable',
  },
  {
    name: 'MarketingPage',
    slug: 'marketing-page',
    kind: 'page',
    category: null,
    description:
      'A complete marketing page composing a hero, a feature grid, a KPI row, a plan comparison and a closing call to action.',
    source: 'src/pages/marketing-page/index.tsx',
    exports: ['MarketingPage'],
    status: 'stable',
  },
  {
    name: 'DashboardPage',
    slug: 'dashboard-page',
    kind: 'page',
    category: null,
    description:
      'A full dashboard screen composing the app shell, a page header, a KPI row and a data table.',
    source: 'src/pages/dashboard-page/index.tsx',
    exports: ['DashboardPage'],
    status: 'stable',
  },
  {
    name: 'SettingsPage',
    slug: 'settings-page',
    kind: 'page',
    category: null,
    description:
      'A full settings screen composing the app shell, a page header and tabs of grouped settings forms.',
    source: 'src/pages/settings-page/index.tsx',
    exports: ['SettingsPage'],
    status: 'stable',
  },
  {
    name: 'AuthPage',
    slug: 'auth-page',
    kind: 'page',
    category: null,
    description:
      'A full authentication screen composing a sign-in form with an optional supporting card.',
    source: 'src/pages/auth-page/index.tsx',
    exports: ['AuthPage'],
    status: 'stable',
  },
  {
    name: 'NotFoundPage',
    slug: 'not-found-page',
    kind: 'page',
    category: null,
    description:
      'A complete not-found screen: the status code as the heading of the page, one sentence about what happened, and the ways out.',
    source: 'src/pages/not-found-page/index.tsx',
    exports: ['NotFoundPage'],
    status: 'stable',
  },
  {
    name: 'BlogPostPage',
    slug: 'blog-post-page',
    kind: 'page',
    category: null,
    description:
      'A complete blog post screen: title, standfirst, byline with both the display and the machine date, the body at the measure and the trail to the neighbouring posts.',
    source: 'src/pages/blog-post-page/index.tsx',
    exports: ['BlogPostPage'],
    status: 'stable',
  },
  {
    name: 'DocsShell',
    slug: 'docs-shell',
    kind: 'page',
    category: null,
    description:
      'A documentation screen: a navigation rail whose shape arrives as data, the document at the measure, a contents rail, and a pager derived from the navigation rather than passed.',
    source: 'src/pages/docs-shell/index.tsx',
    exports: ['DocsShell'],
    status: 'stable',
  },
]

/** Returns the catalogue ordered for display and keyed for lookup. */
export function buildCatalog(items: readonly CatalogItem[] = catalog): CatalogItem[] {
  return [...items].sort((a, b) => a.name.localeCompare(b.name))
}

export const catalogBySlug: ReadonlyMap<string, CatalogItem> = new Map(
  catalog.map((item) => [item.slug, item]),
)
