// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as Progress } from 'antd/es/progress/index.js';
export type { ProgressProps } from 'antd/es/progress/index.js';
