// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as AutoComplete } from 'antd/es/auto-complete/index.js';
export type { AutoCompleteProps } from 'antd/es/auto-complete/index.js';
