/**
 * Theme scoping cost probe (ticket 08).
 *
 * Reads the CURRENT emitted per-pack CSS out of packages/tokens/dist and rewrites
 * only the selector line for each candidate mechanism, then reports raw and gzip
 * byte counts. The declarations are byte-identical across candidates, so the
 * difference measured is the selector cost, not the token cost.
 *
 * Run:  node measure.mjs
 * It also writes the generated bundles to candidates/ for the HTML demo.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { gzipSync } from 'node:zlib'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const DIST = path.join(HERE, '..', '..', '..', '..', 'packages', 'tokens', 'dist')
const OUT = path.join(HERE, 'candidates')

const PACKS = ['blush', 'mint', 'lavender', 'sky', 'peach']
const MODES = ['light', 'dark']

const BANNER =
  '/*\n * Generated by @ds/tokens. Do not edit by hand.\n * Source: packages/tokens/src  (DTCG 2025.10)\n */\n\n'

/** Everything between the first `{` and the last `}` of a ds/css-vars file. */
function body(css) {
  const start = css.indexOf('{')
  const end = css.lastIndexOf('}')
  return css.slice(start + 1, end).replace(/^\n/, '').replace(/\n$/, '')
}

async function read(mode, id) {
  const file = id === 'default'
    ? path.join(DIST, `${mode}.css`)
    : path.join(DIST, 'themes', id, `${mode}.css`)
  return body(await readFile(file, 'utf8'))
}

/** Selector per candidate. `id === 'default'` is the base pack (absence of data-pack). */
const CANDIDATES = {
  // (a) root attribute only — today's shape, axis renamed to data-pack
  'root-attribute': (id, mode) => {
    if (id === 'default') return mode === 'dark' ? '.dark' : ':root'
    return mode === 'dark' ? `.dark[data-pack="${id}"]` : `:root[data-pack="${id}"]`
  },
  // (b) root class only
  'root-class': (id, mode) => {
    if (id === 'default') return mode === 'dark' ? '.dark' : ':root'
    return mode === 'dark' ? `.dark.prism-pack-${id}` : `.prism-pack-${id}`
  },
  // (c) attribute-agnostic, also matches descendants
  'attribute-agnostic': (id, mode) => {
    if (id === 'default') return mode === 'dark' ? '.dark' : ':root'
    return mode === 'dark' ? `[data-pack="${id}"].dark` : `[data-pack="${id}"]`
  },
}

/** Order: base light, base dark, then per pack light, dark. */
function render(candidate) {
  const selector = CANDIDATES[candidate]
  const blocks = []
  for (const id of ['default', ...PACKS]) {
    for (const mode of MODES) {
      blocks.push({ id, mode, selector: selector(id, mode) })
    }
  }
  return Promise.all(
    blocks.map(async (b) => ({ ...b, css: `${b.selector} {\n${await read(b.mode, b.id)}\n}` })),
  )
}

/** A single concatenated bundle: one banner, then every block. */
function bundle(blocks) {
  return BANNER + blocks.map((b) => b.css).join('\n\n') + '\n'
}

/** The five selectable packs only (2 modes each), no base default. */
function fivePackBundle(blocks) {
  const five = blocks.filter((b) => b.id !== 'default')
  return BANNER + five.map((b) => b.css).join('\n\n') + '\n'
}

const kb = (n) => (n / 1024).toFixed(2)
const gz = (s) => gzipSync(Buffer.from(s), { level: 9 }).length

await mkdir(OUT, { recursive: true })

const results = {}
for (const candidate of Object.keys(CANDIDATES)) {
  const blocks = await render(candidate)
  const all = bundle(blocks)
  const five = fivePackBundle(blocks)
  results[candidate] = {
    selectors: blocks.length,
    allRaw: Buffer.byteLength(all),
    allGz: gz(all),
    fiveRaw: Buffer.byteLength(five),
    fiveGz: gz(five),
    css: all,
  }
  await writeFile(path.join(OUT, `${candidate}.css`), all, 'utf8')
}

// (d) inline resolved values bound to a style attribute: the cost is the shipped
// value table (themes/index.js), not CSS. Each themed subtree also duplicates the
// values into the DOM, so the bundle is a floor, not the whole cost.
const inlineJs = await readFile(path.join(DIST, 'themes', 'index.js'), 'utf8')
results['inline-values'] = {
  selectors: 0,
  jsRaw: Buffer.byteLength(inlineJs),
  jsGz: gz(inlineJs),
}

const header = [
  ['candidate', 'selectors', 'all raw B', 'all gzip B', '5-pack raw B', '5-pack gzip B'],
  ['root-attribute', results['root-attribute'].selectors, results['root-attribute'].allRaw, results['root-attribute'].allGz, results['root-attribute'].fiveRaw, results['root-attribute'].fiveGz],
  ['root-class', results['root-class'].selectors, results['root-class'].allRaw, results['root-class'].allGz, results['root-class'].fiveRaw, results['root-class'].fiveGz],
  ['attribute-agnostic', results['attribute-agnostic'].selectors, results['attribute-agnostic'].allRaw, results['attribute-agnostic'].allGz, results['attribute-agnostic'].fiveRaw, results['attribute-agnostic'].fiveGz],
  ['inline-values', 0, `JS ${results['inline-values'].jsRaw}`, `JS ${results['inline-values'].jsGz}`, '-', '-'],
]

const cols = [24, 9, 11, 11, 13, 14]
const table = header
  .map((row) => row.map((c, i) => String(c).padEnd(cols[i])).join(''))
  .join('\n')

console.log(table)
console.log('')
console.log(`all  = base default + 5 packs, 2 modes each (12 blocks, one banner)`)
console.log(`5pk  = the 5 selectable packs only, 2 modes each (10 blocks, one banner)`)
console.log(`gzip = zlib level 9, on the concatenated bundle`)
console.log(`sizes are bytes; 'all raw B' column is bytes, divide by 1024 for KiB`)
console.log(`wrote ${Object.keys(CANDIDATES).length} candidate bundles to ${path.relative(process.cwd(), OUT)}`)

await writeFile(
  path.join(HERE, 'results.json'),
  JSON.stringify(
    Object.fromEntries(
      Object.entries(results).map(([k, v]) => [k, { ...v, css: undefined }]),
    ),
    null,
    2,
  ) + '\n',
  'utf8',
)
