// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as Pagination } from 'antd/es/pagination/index.js';
export type { PaginationProps } from 'antd/es/pagination/index.js';
