// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as Skeleton } from 'antd/es/skeleton/index.js';
export type { SkeletonProps } from 'antd/es/skeleton/index.js';
