/**
 * The MCP lane's pre-build stamps.
 *
 * Ticket 13 section 8 keeps the stamp out of the corpus `dist` so the corpus
 * stays byte-deterministic, and derives it from the source commit date plus the
 * corpus version rather than a file mtime. The generated module is gitignored;
 * if git or the corpus is unavailable the stamp is `undefined` and
 * `list_items` omits the `(built ...)` clause instead of fabricating a date.
 *
 * The second stamp is this package's own version, and it is the one input here
 * that cannot be optional. A hand-written `SERVER_VERSION` was a second place
 * every release had to remember, and it read `0.1.0` for a package published as
 * `0.2.0`: the server told every consumer a version it had stopped being.
 * Deriving it here makes the manifest the one place a release writes a version,
 * and a release cannot leave this one stale because the build, the type-check
 * and the tests all run this step first. It also has to be a build step rather
 * than a read at import time, because this package's logic is served from the
 * site Worker, where there is no filesystem to read.
 *
 * Run before the package build: node scripts/stamp-built.mjs
 */
import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const PKG = path.resolve(HERE, '..')
const REPO = path.resolve(PKG, '..', '..')
const OUT = path.join(PKG, 'src', 'generated', 'built.ts')
const VERSION_OUT = path.join(PKG, 'src', 'generated', 'server-version.ts')

function commitDate() {
  try {
    const out = execFileSync('git', ['log', '-1', '--format=%cs'], {
      cwd: REPO,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    })
    const date = out.trim()
    return /^\d{4}-\d{2}-\d{2}$/.test(date) ? date : undefined
  } catch {
    return undefined
  }
}

function readVersion(file) {
  if (!existsSync(file)) return undefined
  try {
    const value = JSON.parse(readFileSync(file, 'utf8')).version
    return typeof value === 'string' ? value : undefined
  } catch {
    return undefined
  }
}

function corpusVersion() {
  const fromStore = readVersion(path.join(REPO, 'packages', 'llms', 'dist', 'data.json'))
  if (fromStore) return fromStore
  return readVersion(path.join(REPO, 'packages', 'llms', 'package.json'))
}

/**
 * This package's own published version, the one input with no fallback.
 *
 * A client reads the reported version to decide what the server supports, so an
 * unreadable manifest is a build failure rather than a default. A default here
 * would be the stale version with extra steps, which is the defect this stamp
 * exists to remove.
 */
function serverVersion() {
  const value = readVersion(path.join(PKG, 'package.json'))
  if (value === undefined) {
    throw new Error(
      'prism-mcp-server: this package\'s own package.json carries no readable version, so the ' +
        'server has no version to report to a client. A client reads that version to decide what ' +
        'the server supports, so it is stamped from the manifest rather than defaulted.',
    )
  }
  return value
}

const date = commitDate()
const corpus = corpusVersion()
// Both inputs are required: the stamp is a claim about a specific corpus build.
const built = date && corpus ? date : undefined
const server = serverVersion()

const body = `// Generated by scripts/stamp-built.mjs. Gitignored; do not edit.
// Derived from the corpus source commit date plus the corpus version. The
// fallback is undefined (git or the corpus unavailable), which makes
// list_items omit the (built ...) clause rather than fabricate a date.
export const BUILT: string | undefined = ${built ? JSON.stringify(built) : 'undefined'}
export const BUILT_CORPUS: string | undefined = ${corpus ? JSON.stringify(corpus) : 'undefined'}
`

const version = `// Generated by scripts/stamp-built.mjs. Gitignored; do not edit.
// Derived from this package's own package.json, which is the single place a
// release writes a version. There is no fallback value: an unreadable manifest
// throws in the step above rather than stamping a version this package is not.
export const SERVER_VERSION: string = ${JSON.stringify(server)}
`

mkdirSync(path.dirname(OUT), { recursive: true })
writeFileSync(OUT, body)
writeFileSync(VERSION_OUT, version)
console.log(
  `prism-mcp-server: build stamp ${built ?? 'undefined'} (corpus ${corpus ?? 'undefined'}), ` +
    `version ${server}`,
)
