/**
 * The MCP lane's build stamp.
 *
 * Ticket 13 section 8 keeps the stamp out of the corpus `dist` so the corpus
 * stays byte-deterministic, and derives it from the source commit date plus the
 * corpus version rather than a file mtime. The generated module is gitignored;
 * if git or the corpus is unavailable the stamp is `undefined` and
 * `list_items` omits the `(built ...)` clause instead of fabricating a date.
 *
 * Run before the package build: node scripts/stamp-built.mjs
 */
import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const PKG = path.resolve(HERE, '..')
const REPO = path.resolve(PKG, '..', '..')
const OUT = path.join(PKG, 'src', 'generated', 'built.ts')

function commitDate() {
  try {
    const out = execFileSync('git', ['log', '-1', '--format=%cs'], {
      cwd: REPO,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    })
    const date = out.trim()
    return /^\d{4}-\d{2}-\d{2}$/.test(date) ? date : undefined
  } catch {
    return undefined
  }
}

function readVersion(file) {
  if (!existsSync(file)) return undefined
  try {
    const value = JSON.parse(readFileSync(file, 'utf8')).version
    return typeof value === 'string' ? value : undefined
  } catch {
    return undefined
  }
}

function corpusVersion() {
  const fromStore = readVersion(path.join(REPO, 'packages', 'llms', 'dist', 'data.json'))
  if (fromStore) return fromStore
  return readVersion(path.join(REPO, 'packages', 'llms', 'package.json'))
}

const date = commitDate()
const corpus = corpusVersion()
// Both inputs are required: the stamp is a claim about a specific corpus build.
const built = date && corpus ? date : undefined

const body = `// Generated by scripts/stamp-built.mjs. Gitignored; do not edit.
// Derived from the corpus source commit date plus the corpus version. The
// fallback is undefined (git or the corpus unavailable), which makes
// list_items omit the (built ...) clause rather than fabricate a date.
export const BUILT: string | undefined = ${built ? JSON.stringify(built) : 'undefined'}
export const BUILT_CORPUS: string | undefined = ${corpus ? JSON.stringify(corpus) : 'undefined'}
`

mkdirSync(path.dirname(OUT), { recursive: true })
writeFileSync(OUT, body)
console.log(
  `prism-mcp-server: build stamp ${built ?? 'undefined'} (corpus ${corpus ?? 'undefined'})`,
)
