// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as Popconfirm } from 'antd/es/popconfirm/index.js';
export type { PopconfirmProps } from 'antd/es/popconfirm/index.js';
