import { Archivo, JetBrains_Mono } from 'next/font/google';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import type { Metadata } from 'next';
import type { ReactNode } from 'react';

import { SiteFooter, SiteHeader } from '@/components/SiteHeader';
import { SiteThemeProvider } from '@/components/SiteThemeProvider';
import { DEFAULT_MODE, DEFAULT_PACK, THEME_BOOTSTRAP_SCRIPT, themeClass } from '@/lib/theme';

// prism-ui's font faces / display width-axis / dither patterns (ADR-0001).
// Its @font-face declarations resolve to /fonts/*.woff2 — shipped from
// public/fonts (the latin variable subsets next/font also self-hosts for
// --font-archivo / --font-jetbrains below), because prism-tokens' antd
// fontFamily names 'Archivo Variable' directly.
import '@nanisoft/prism-ui/styles.css';
// Four pre-baked antd variable rulesets (one per pack × mode, keyed by the
// `prism-<pack>-<mode>` cssVar class) — generated by scripts/bake-antd-css.mjs.
import './antd-vars.css';
import './globals.css';

const archivo = Archivo({
  subsets: ['latin'],
  // The width axis IS the refraction (ADR-0001) — wght comes implicitly.
  axes: ['wdth'],
  variable: '--font-archivo',
  display: 'swap',
});

const jetbrains = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrains',
  display: 'swap',
});

export const metadata: Metadata = {
  title: {
    default: 'Prism — one design language, many expressions',
    template: '%s · Prism',
  },
  description:
    "NaniSoft's Ant Design–based design system: tokens, components, blocks, and pages, with docs and an LLM/agent surface.",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={themeClass(DEFAULT_PACK, DEFAULT_MODE)}>
      <body className={`${archivo.variable} ${jetbrains.variable}`}>
        {/* Blocking, before paint: applies the stored (or default) theme class —
            the flash-free half of ticket 02's class-swap recipe. */}
        <script dangerouslySetInnerHTML={{ __html: THEME_BOOTSTRAP_SCRIPT }} />
        <AntdRegistry>
          <SiteThemeProvider>
            <SiteHeader />
            <main className="site-main">{children}</main>
            <SiteFooter />
          </SiteThemeProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
