// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as Descriptions } from 'antd/es/descriptions/index.js';
export type { DescriptionsProps } from 'antd/es/descriptions/index.js';
