// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as Segmented } from 'antd/es/segmented/index.js';
export type { SegmentedProps } from 'antd/es/segmented/index.js';
