// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as Timeline } from 'antd/es/timeline/index.js';
export type { TimelineProps } from 'antd/es/timeline/index.js';
