// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as Collapse } from 'antd/es/collapse/index.js';
export type { CollapseProps } from 'antd/es/collapse/index.js';
