/**
 * The container-namespace gate, run as a process over staged defects.
 *
 * A gate that has never been red is not evidence, and this one is written against a
 * failure that produced no symptom at all: two container namespaces shipped, three
 * of Tailwind's steps were numerically identical to three authored widths, and
 * nothing rendered differently. So every rule is proved here by feeding it an
 * artefact that breaks it, and the artefacts are hand-written rather than built,
 * because the thing under test is what the gate can SEE in a stylesheet and a real
 * Tailwind build of a broken tree would resolve the defect away before the gate ran.
 *
 * **The shipped script is copied rather than reimplemented**, so what runs is the
 * file that runs in `pnpm check`, and it resolves its roots from its own location,
 * which is also how each case proves the working directory cannot change what it
 * read. Each staged tree carries the token source, the token theme and this
 * package's own source beside it, because the run fails on a missing file rather
 * than reading what is not there.
 *
 * **Tailwind's step list is read out of the installed framework, not restated.** A
 * fixture that lists the steps would only prove the gate agrees with this file, so
 * the staged tree resolves `tailwindcss` from the real installation and every case
 * is measured against the framework the repository actually pins.
 *
 * Run: pnpm --filter @nanisoft/prism-ui test
 */
import { spawnSync, type SpawnSyncReturns } from 'node:child_process'
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'

const REPO = path.resolve(import.meta.dirname, '..', '..', '..')
const PKG = path.join(REPO, 'packages', 'ui')
const TOKENS = path.join(REPO, 'packages', 'tokens')
const GATE = 'check-container-namespace.mjs'

/**
 * The eight authored containers, in the order the token build emits them.
 *
 * Written out rather than read from the staged token source, because the point of
 * the clean case is to compare the SHEET against an authority and a fixture that
 * reads its own answer proves nothing.
 */
const AUTHORED = ['page', 'measure', 'measure-narrow', 'overlay-panel', 'overlay-dialog', 'overlay-form', 'overlay-palette', 'overlay-media']
const VALUES: Record<string, string> = {
  page: '72rem',
  measure: '42rem',
  'measure-narrow': '36rem',
  'overlay-panel': '24rem',
  'overlay-dialog': '28rem',
  'overlay-form': '32rem',
  'overlay-palette': '36rem',
  'overlay-media': '64rem',
}

const themeBlock = (names: string[], extra = '') =>
  [
    '@layer theme {',
    '  :root, :host {',
    '    --spacing: 0.25rem;',
    ...names.map((name) => `    --container-${name}: ${VALUES[name] ?? '72rem'};`),
    extra,
    '  }',
    '}',
    '',
  ]
    .filter((line) => line !== '')
    .join('\n')

/** A stylesheet that also carries one `max-w` rule per container. */
const sheet = (names: string[], options: { theme?: string; utilities?: string[] } = {}) => {
  const utilities = options.utilities ?? names
  return [
    '/*! tailwindcss v4.3.3 | MIT License | https://tailwindcss.com */',
    '@layer theme, base, components, utilities;',
    options.theme ?? themeBlock(names),
    '@layer utilities {',
    ...utilities.map((name) => `  .max-w-${name} { max-width: var(--container-${name}); }`),
    '}',
    '',
  ].join('\n')
}

const TOKEN_THEME = (names: string[], order: 'close-first' | 'close-last' = 'close-first') => {
  const lines = names.map((name) => `  --container-${name}: ${VALUES[name]};`)
  const close = '  --container-*: initial;'
  return [
    '/*',
    ' * Generated by @nanisoft/prism-tokens. Do not edit by hand.',
    ' */',
    '@theme static {',
    '  --spacing: 0.25rem;',
    ...(order === 'close-first' ? [close, ...lines] : [...lines, close]),
    '}',
    '',
  ].join('\n')
}

const LAYOUT = JSON.stringify(
  {
    container: {
      $type: 'dimension',
      $description: 'staged',
      ...Object.fromEntries(AUTHORED.map((name) => [name, { $value: { value: 1, unit: 'rem' } }])),
    },
  },
  null,
  2,
)

/** One Component per authored container, so every token has a call site. */
const sourceUsing = (...names: string[]) =>
  names
    .map((name, index) =>
      [
        `export function Probe${index}({ className }: { className?: string }) {`,
        `  return <div className={\`max-w-${name} \${className ?? ''}\`} />`,
        '}',
        '',
      ].join('\n'),
    )
    .join('\n')

const BASELINE = {
  layout: LAYOUT,
  tokenTheme: TOKEN_THEME(AUTHORED),
  sheet: sheet(AUTHORED),
  source: sourceUsing(...AUTHORED),
}

const staged: string[] = []

afterEach(() => {
  for (const dir of staged.splice(0)) rmSync(dir, { force: true, recursive: true })
})

/** A staged tree holding the shipped gate and one artefact set. */
function stage(files: Partial<typeof BASELINE>): SpawnSyncReturns<string> {
  const dir = mkdtempSync(path.join(os.tmpdir(), 'prism-containers-'))
  staged.push(dir)

  const write = (relative: string, source: string) => {
    const to = path.join(dir, relative)
    mkdirSync(path.dirname(to), { recursive: true })
    writeFileSync(to, source)
  }

  write(`packages/ui/scripts/${GATE}`, readFileSync(path.join(PKG, 'scripts', GATE), 'utf8'))
  write('packages/tokens/src/foundation/layout.tokens.json', files.layout ?? BASELINE.layout)
  write('packages/tokens/dist/theme.css', files.tokenTheme ?? BASELINE.tokenTheme)
  write('packages/ui/dist/styles.css', files.sheet ?? BASELINE.sheet)
  write('packages/ui/src/probe.tsx', files.source ?? BASELINE.source)

  return spawnSync(process.execPath, [path.join(dir, 'packages', 'ui', 'scripts', GATE)], {
    cwd: REPO,
    encoding: 'utf8',
  })
}

describe('the container-namespace gate', () => {
  it('passes on the real tree, and prints both halves of what it compared', () => {
    const result = spawnSync(process.execPath, [path.join(PKG, 'scripts', GATE)], {
      cwd: REPO,
      encoding: 'utf8',
    })

    expect(result.stderr).toBe('')
    expect(result.status).toBe(0)
    expect(result.stdout).toContain('@layer theme declares 8 container variable(s)')
    expect(result.stdout).toContain('close: --container-*: initial at offset')
    expect(result.stdout).toContain('8 of 8 authored container(s) reached by a call site')
    // The thirteen steps are read out of the installed framework, so the count is
    // the framework's to change and this file's not.
    expect(result.stdout).toMatch(/Tailwind's own 13 step\(s\), read from the installed default theme/)
    expect(result.stdout).toContain("none of\n  Tailwind's 13 own steps is declared or read")
  })

  it('passes on a staged tree that is already correct', () => {
    const result = stage({})

    expect(result.stderr).toBe('')
    expect(result.status).toBe(0)
  })

  const retired = ['sm', 'md', 'lg', 'xl', '2xl', '5xl', '6xl']

  it('fails a Tailwind step the sheet declares beside an authored width', () => {
    // The defect this gate was written for: 6xl is 72rem and so is page, so a
    // retune of page would move one surface and not the other.
    const result = stage({
      sheet: sheet(AUTHORED, {
        theme: themeBlock(AUTHORED, '    --container-6xl: 72rem;'),
        utilities: [...AUTHORED, '6xl'],
      }),
    })

    expect(result.status).toBe(1)
    expect(result.stderr).toContain('the shipped stylesheet declares `--container-6xl`')
    expect(result.stderr).toContain('two spellings of a width are shipping at once')
  })

  it('fails every step Tailwind ships, not only the three that collided', () => {
    for (const step of retired) {
      const result = stage({
        sheet: sheet(AUTHORED, {
          theme: themeBlock(AUTHORED, `    --container-${step}: 24rem;`),
          utilities: [...AUTHORED, step],
        }),
      })

      expect(result.status, step).toBe(1)
      expect(result.stderr, step).toContain(`declares \`--container-${step}\``)
    }
  })

  it('fails a rule reading a step the sheet no longer declares', () => {
    // The signature of a retired class name surviving in a JSDoc block, because
    // Tailwind extracts this package's comments as well as its code.
    const result = stage({
      sheet: `${sheet(AUTHORED)}\n.layer { max-width: var(--container-6xl); }\n`,
    })

    expect(result.status).toBe(1)
    expect(result.stderr).toContain('has a rule reading `var(--container-6xl)`')
    expect(result.stderr).toContain('a retired class name written down in prose')
  })

  it('fails a token theme that does not close the namespace', () => {
    const result = stage({
      tokenTheme: TOKEN_THEME(AUTHORED).replace('  --container-*: initial;\n', ''),
    })

    expect(result.status).toBe(1)
    expect(result.stderr).toContain('does not close the container namespace')
  })

  it('fails a token theme that writes the close after the authored entries', () => {
    const result = stage({ tokenTheme: TOKEN_THEME(AUTHORED, 'close-last') })

    expect(result.status).toBe(1)
    expect(result.stderr).toContain('clears the authored widths as well as')
  })

  it('fails a sheet that emits no rule for a width a call site writes', () => {
    const result = stage({ sheet: sheet(AUTHORED.filter((name) => name !== 'page')) })

    expect(result.status).toBe(1)
    expect(result.stderr).toContain('`max-w-page` names `--container-page`')
    expect(result.stderr).toContain('the shipped stylesheet emits no rule for it')
  })

  it('fails an authored container nothing reaches', () => {
    const result = stage({ source: sourceUsing('page') })

    expect(result.status).toBe(1)
    expect(result.stderr).toContain('--container-overlay-media is authored and emitted and no surface')
    expect(result.stderr).toContain('Either a surface should name it or it should not be authored.')
  })

  it('fails a sheet carrying a container the token source does not author', () => {
    const result = stage({
      sheet: sheet(AUTHORED, {
        theme: themeBlock([...AUTHORED, 'overlay-panel-wide']),
        utilities: [...AUTHORED, 'overlay-panel-wide'],
      }),
    })

    expect(result.status).toBe(1)
    expect(result.stderr).toContain('emitted without an authored source entry: overlay-panel-wide')
  })

  it('fails loudly rather than checking nothing when the sheet was never built', () => {
    const dir = mkdtempSync(path.join(os.tmpdir(), 'prism-containers-'))
    staged.push(dir)
    const write = (relative: string, source: string) => {
      const to = path.join(dir, relative)
      mkdirSync(path.dirname(to), { recursive: true })
      writeFileSync(to, source)
    }
    write(`packages/ui/scripts/${GATE}`, readFileSync(path.join(PKG, 'scripts', GATE), 'utf8'))
    write('packages/tokens/src/foundation/layout.tokens.json', BASELINE.layout)
    write('packages/tokens/dist/theme.css', BASELINE.tokenTheme)
    write('packages/ui/src/probe.tsx', BASELINE.source)
    // No `dist/styles.css` at all, which is what a clean checkout looks like to this gate.


    const result = spawnSync(process.execPath, [path.join(dir, 'packages', 'ui', 'scripts', GATE)], {
      cwd: REPO,
      encoding: 'utf8',
    })

    expect(result.status).toBe(1)
    expect(result.stderr).toContain('packages/ui/dist/styles.css does not exist, so this run has nothing to check')
    expect(result.stderr).toContain('Run `pnpm build` first.')
  })

  it('fails rather than judging every name when the token source has no containers', () => {
    const result = stage({ layout: JSON.stringify({ container: { $type: 'dimension' } }, null, 2) })

    expect(result.status).toBe(1)
    expect(result.stderr).toContain('the authored `container` group in')
    expect(result.stderr).toContain('is empty, so every width in the')
  })

  it('reads its artefacts from its own location, not the working directory', () => {
    const fromPackage = spawnSync(process.execPath, [path.join(PKG, 'scripts', GATE)], {
      cwd: PKG,
      encoding: 'utf8',
    })
    const fromRoot = spawnSync(process.execPath, [path.join(PKG, 'scripts', GATE)], {
      cwd: REPO,
      encoding: 'utf8',
    })

    expect(fromPackage.status).toBe(0)
    expect(fromPackage.stdout).toBe(fromRoot.stdout)
  })
})
