// Parity across antd upgrades (ADR-0003): the generated pass-through set is
// pinned to the installed antd in BOTH directions, wrappers cannot overlap
// pass-throughs, and the catalog cannot drift from the exports.

import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as antd from 'antd';

import { antdCategories, buildCatalog, componentCategories, wrappedComponents, type PassThroughItem } from '../src/wrapped-registry.js';
import type { PrismCategory } from '../src/wrapped-registry.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, '..');
const componentsDir = path.join(root, 'src', 'components');

// Mirrors scripts/generateAntdExports.mjs's allowlist — the non-component
// surfaces that must never become proxy components.
const NON_COMPONENT_EXPORTS = new Set([
  'ConfigProvider',
  'App',
  'theme',
  'message',
  'notification',
  'version',
  'Typography.Text',
  'Form.Item',
  'Table.Column',
]);

const WRAPPED_ANTD_NAMES = new Set(wrappedComponents.map((w) => w.antdName));

function parseAntdComponents(): string[] {
  const content = fs.readFileSync(path.join(root, 'node_modules', 'antd', 'es', 'index.d.ts'), 'utf8');
  const names: string[] = [];
  for (const match of content.matchAll(/export\s*\{\s*default\s+as\s+([^}]+?)\s*\}\s+from\s+['"]([^'"]+)['"];?/g)) {
    const name = match[1].trim();
    if (!NON_COMPONENT_EXPORTS.has(name) && !WRAPPED_ANTD_NAMES.has(name)) names.push(name);
  }
  return names.sort();
}

function parseGeneratedBarrel(): { values: string[]; proxyDirs: string[] } {
  const content = fs.readFileSync(path.join(root, 'src', 'generated', 'antd-components.ts'), 'utf8');
  const values: string[] = [];
  for (const match of content.matchAll(/export\s*\{\s*([A-Za-z][A-Za-z0-9]*)\s*\}\s*from\s+'antd';/g)) {
    values.push(match[1]);
  }
  const proxyDirs = fs
    .readdirSync(componentsDir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();
  return { values: values.sort(), proxyDirs };
}

describe('codegen parity', () => {
  const antdComponents = parseAntdComponents();
  const { values: generated, proxyDirs } = parseGeneratedBarrel();

  it('generates exactly the unwrapped component set of the installed antd (both directions)', () => {
    expect(generated).toEqual(antdComponents);
  });

  it('emits one proxy module per generated component, and nothing else', () => {
    const expectedDirs = [...generated.map(kebab), 'display-title'].sort();
    expect(proxyDirs).toEqual(expectedDirs);
    for (const dir of proxyDirs) {
      expect(fs.existsSync(path.join(componentsDir, dir, 'index.ts')), `missing proxy: ${dir}/index.ts`).toBe(true);
    }
  });

  it('a wrapped component never ships as a pass-through', () => {
    for (const wrapper of wrappedComponents) {
      expect(generated).not.toContain(wrapper.antdName);
    }
  });

  it('hand-written component files never import antd directly (only generated proxies and wrappers do)', () => {
    for (const dir of proxyDirs) {
      if (dir === 'display-title') continue;
      const content = fs.readFileSync(path.join(componentsDir, dir, 'index.ts'), 'utf8');
      expect(content, `${dir}/index.ts must be a generated proxy`).toMatch(/^\/\/ GENERATED by scripts\/generateAntdExports\.mjs/);
    }
  });

  it('every generated component resolves on the installed antd', () => {
    for (const name of generated) {
      expect(antd, `${name} missing on installed antd`).toHaveProperty(name);
    }
  });
});

describe('registry + catalog', () => {
  const items: PassThroughItem[] = parseAntdComponents().map((name) => ({ name, id: kebab(name) }));
  const catalog = buildCatalog(items);

  it('categorizes every item into antd’s six categories plus the Prism group', () => {
    const allowed: ReadonlySet<PrismCategory> = new Set<PrismCategory>([...antdCategories, 'prism']);
    for (const entry of catalog) {
      expect(allowed.has(entry.category), `${entry.name}: unknown category "${entry.category}"`).toBe(true);
    }
  });

  it('carries antdBase on pass-throughs only (wrappers ride on their registry entry)', () => {
    for (const entry of catalog) {
      if (entry.wrapped) {
        expect(entry.antdBase).toBeUndefined();
        expect(entry.wrapped.antdName).toBeTruthy();
      } else if (entry.layer === 'components') {
        expect(entry.antdBase).toBe(entry.name);
      } else {
        expect(entry.antdBase).toBeUndefined();
      }
    }
  });

  it('contains exactly one entry per cataloged item, with no duplicates', () => {
    const names = catalog.map((e) => e.name);
    expect(new Set(names).size).toBe(names.length);
    for (const block of ['ComponentDemo', 'PageHeader', 'SiteHeader', 'SiteFooter']) expect(names).toContain(block);
    for (const page of ['DocsShell', 'BlogLayout']) expect(names).toContain(page);
    expect(names).toContain('DisplayTitle');
  });

  it('keeps the hand-maintained category table in lockstep with the generated set', () => {
    for (const name of parseAntdComponents()) {
      expect(componentCategories[name], `${name} missing from componentCategories`).toBeTruthy();
    }
    const generatedNames = new Set(parseAntdComponents());
    for (const name of Object.keys(componentCategories)) {
      const known =
        generatedNames.has(name) ||
        ['DisplayTitle', 'ComponentDemo', 'PageHeader', 'SiteHeader', 'SiteFooter', 'DocsShell', 'BlogLayout'].includes(name);
      expect(known, `${name} in componentCategories but not a prism-ui item`).toBe(true);
    }
  });

  it('keeps wrapper parity: removedProps non-empty only under api-narrowing', () => {
    for (const wrapper of wrappedComponents) {
      const narrows = wrapper.justification === 'api-narrowing';
      expect((wrapper.removedProps?.length ?? 0) > 0).toBe(narrows);
    }
  });
});

function kebab(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}
