// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as Checkbox } from 'antd/es/checkbox/index.js';
export type { CheckboxProps } from 'antd/es/checkbox/index.js';
