import type { Metadata } from 'next'
import type { ReactNode } from 'react'
import type { TOCItemType } from 'fumadocs-core/toc'
import { notFound } from 'next/navigation'

import { ApiTable } from '@/components/api-table'
import { CatalogueIndex } from '@/components/catalogue-index'
import { DocsShell } from '@/components/docs-shell'
import { ItemHeader } from '@/components/item-header'
import { getMDXComponents } from '@/components/mdx'
import type { CataloguePageData } from '@/lib/catalogue'
import { flattenNav, projectNav } from '@/lib/nav'
import { source } from '@/lib/source'

export function generateStaticParams() {
  return source.generateParams()
}

export const dynamicParams = false

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string[] }>
}): Promise<Metadata> {
  const { slug } = await params
  const page = source.getPage(slug)
  return page ? { title: (page.data.title as string | undefined) ?? undefined } : {}
}

type ProseBody = (props: { components?: Record<string, unknown> }) => ReactNode

/**
 * What every page in the routed tree carries.
 *
 * `kind`, `category`, `status`, `exports`, `source`, `slug` and `name` are the
 * Catalogue's words, merged into an Item page's data by `content-tree.ts` from
 * `buildCatalog()`. The collection's schema strips a `kind` or a `category` out
 * of frontmatter, so this cast reads a shape a maintainer cannot write into a
 * file: the discriminator below is a key only the merge adds, which is why
 * "is this an Item page" is answered by the data rather than by which collection
 * or which loader the page came from.
 */
type RoutedData = Partial<CataloguePageData> & {
  /** The file opens with its own heading, so the frame adds none. */
  selfTitled?: boolean
  body?: ProseBody
  toc?: TOCItemType[]
}

export default async function Page({ params }: { params: Promise<{ slug: string[] }> }) {
  const { slug } = await params
  const page = source.getPage(slug)

  // The canonical fumadocs check, before returning and never inside a Suspense
  // boundary, so an unknown slug is a real not-found rather than a soft 404.
  if (!page) notFound()

  // The tree is the navigation's one source, read here because this is the one
  // module that can: the routing tree is compiled by the bundler plugin, so it
  // does not exist outside it. The projection refuses to return a partial
  // navigation, which is what turns a page the ordering forgot into a failed
  // render rather than a green build with a page missing from the sidebar.
  const sections = projectNav(source.getPageTree())
  const flat = flattenNav(sections)
  const components = getMDXComponents()
  const data = page.data as RoutedData

  // A Section landing page, generated by the Catalogue because no file says what
  // the Section holds. It is the only page with no body, and it is the only page
  // a reader reaches at a Section's own route.
  if (data.sectionIndex === true && data.kind !== undefined) {
    return (
      <CatalogueIndex kind={data.kind} sections={sections} flat={flat} currentUrl={page.url} />
    )
  }

  // An Item page is its documentation, read by the one collection and carrying
  // the Catalogue's words. The body is the file's own, so there is no second
  // collection to look in and no slug to join: the page a reader got and the
  // document that holds its prose are one thing.
  if (data.kind !== undefined && data.slug !== undefined) {
    const ItemBody = data.body
    return (
      <DocsShell sections={sections} currentUrl={page.url} flat={flat} toc={data.toc}>
        <ItemHeader
          name={data.name ?? data.title ?? data.slug}
          description={data.description ?? ''}
          kind={data.kind}
          category={data.category ?? null}
          status={data.status ?? 'stable'}
        />

        {ItemBody ? (
          <div className="prose">
            <ItemBody components={components} />
          </div>
        ) : null}

        <section className="flex flex-col gap-3">
          <h2 className="text-lg font-semibold tracking-tight">API reference</h2>
          <ApiTable slug={data.slug} />
        </section>
      </DocsShell>
    )
  }

  const Body = data.body

  return (
    <DocsShell sections={sections} currentUrl={page.url} flat={flat} toc={data.toc}>
      {/*
        A page that declares its title in frontmatter has no heading of its own,
        so the frame prints one. A generated page is a published package's own
        `CHANGELOG.md`, byte for byte, and that file begins with the package's
        name: the heading is already in the body, and printing a second one
        above it is the same heading twice. Nothing is dropped from the file
        either way, which is the property the Section is for.
      */}
      {data.selfTitled ? null : (
        <header className="flex flex-col gap-3">
          <h1 className="text-3xl font-semibold tracking-tight">{data.title}</h1>
          {data.description ? (
            <p className="text-muted-foreground max-w-2xl text-lg text-pretty">{data.description}</p>
          ) : null}
        </header>
      )}

      {Body ? (
        <div className="prose">
          <Body components={components} />
        </div>
      ) : null}
    </DocsShell>
  )
}
