// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as Transfer } from 'antd/es/transfer/index.js';
export type { TransferProps } from 'antd/es/transfer/index.js';
