// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as Dropdown } from 'antd/es/dropdown/index.js';
export type { DropdownProps } from 'antd/es/dropdown/index.js';
