// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as BorderBeam } from 'antd/es/border-beam/index.js';
export type { BorderBeamProps } from 'antd/es/border-beam/index.js';
