// GENERATED by scripts/generateAntdExports.mjs - DO NOT EDIT MANUALLY
export { default as InputNumber } from 'antd/es/input-number/index.js';
export type { InputNumberProps } from 'antd/es/input-number/index.js';
