// The demos registry generator: ids are `<section>/<item>/<slug>` (the same
// files prism-llms serves), imports are extensionless relative paths (bundler
// resolution), and the code is embedded verbatim.

import { describe, expect, it } from 'vitest';
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';

import { collectDemos, renderDemosModule, generateDemosRegistry } from '../scripts/lib/generate-demos.mjs';

async function makeContent(): Promise<string> {
  const root = await mkdtemp(path.join(tmpdir(), 'prism-demos-'));
  const content = path.join(root, 'content');
  await mkdir(path.join(content, 'components', 'button', 'demos'), { recursive: true });
  await mkdir(path.join(content, 'blog', 'hello-world', 'demos'), { recursive: true });
  await mkdir(path.join(content, 'docs'), { recursive: true });
  await writeFile(
    path.join(content, 'components', 'button', 'demos', 'basic.tsx'),
    'export default () => <Button />;\n',
  );
  await writeFile(path.join(content, 'blog', 'hello-world', 'demos', 'inline.tsx'), 'export default () => <Tag />;\n');
  await writeFile(path.join(content, 'docs', 'guide.mdx'), '---\ntitle: Guide\n---\n'); // flat guide — no demos dir
  return root;
}

describe('collectDemos', () => {
  it('walks every section, ids by filename slug, sorted', async () => {
    const root = await makeContent();
    try {
      const generatedDir = path.join(root, 'lib', 'generated');
      const contentRoot = path.join(root, 'content');
      const entries = await collectDemos(contentRoot, generatedDir);
      expect(entries.map((entry) => entry.id)).toEqual(['blog/hello-world/inline', 'components/button/basic']);
      const basic = entries[1]!;
      expect(basic.importPath.replace(/\\/g, '/')).toBe('../../content/components/button/demos/basic');
      expect(basic.code).toBe('export default () => <Button />;\n');
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it('tolerates missing sections and empty trees', async () => {
    const root = await mkdtemp(path.join(tmpdir(), 'prism-demos-empty-'));
    try {
      expect(await collectDemos(root, root)).toEqual([]);
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });
});

describe('renderDemosModule', () => {
  it('embeds the component import and verbatim source under one id', () => {
    const module = renderDemosModule([
      { id: 'components/button/basic', importPath: '../../content/components/button/demos/basic', code: 'export default () => 1;\n' },
    ]);
    expect(module).toContain("import Demo0 from '../../content/components/button/demos/basic';");
    expect(module).toContain(
      `"components/button/basic": { Component: Demo0, code: ${JSON.stringify('export default () => 1;\n')} }`,
    );
    expect(module).toContain('export interface DemoEntry');
  });

  it('renders a valid empty registry when no demos exist', () => {
    const module = renderDemosModule([]);
    expect(module).toContain('export const demos: Record<string, DemoEntry> = {');
    expect(module).not.toContain('import Demo');
  });
});

describe('generateDemosRegistry', () => {
  it('writes the module and reports the count', async () => {
    const root = await makeContent();
    try {
      const outFile = path.join(root, 'lib', 'generated', 'demos.ts');
      const count = await generateDemosRegistry(path.join(root, 'content'), outFile);
      expect(count).toBe(2);
      const text = await readFile(outFile, 'utf8');
      expect(text).toContain('"blog/hello-world/inline"');
      expect(text).toContain('GENERATED by apps/site/scripts/generate.mjs');
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });
});
